
 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  
 using System.Reflection;

 [assembly: AssemblyVersion("0.2.13.0")]
 [assembly: AssemblyDescription("$(ProjectDir)")]