



/* < # @ assembly name="EnvDTE" # > < # / * This assembly provides access to Visual Studio project properties. * / # > */

 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  
 using System.Reflection;

 [assembly: AssemblyVersion("0.3.7.9")]
 [assembly: AssemblyFileVersion("0.3.7.9")]
 [assembly: AssemblyDescription("$(ProjectDir)")]